[workspace]
members = ["api", "basic-kernel", "test-kernel", "utils", "xtask"]

[package]
name = "roxy-loader"
version = "0.1.6"
edition = "2024"
description = "Lightweight Rust bootloader for kernel development."
license = "MIT OR Apache-2.0"
repository = "https://github.com/RoxyOS/roxy-loader"
homepage = "https://github.com/RoxyOS/roxy-loader"
documentation = "https://docs.rs/roxy-loader"
readme = "README.md"

[dependencies]
anyhow.workspace = true
elfloader.workspace = true
uefi.workspace = true
roxy-loader-api.workspace = true

[workspace.dependencies]
anyhow = { version = "1", default-features = false }
buddy_system_allocator = "0.13"
cargo-emit = "0.2"
cargo-artifact-dependency = "0.4"
cbindgen = "0.29"
cargo_metadata = "0.23"
clap = { version = "4", features = ["derive"] }
elfloader = "0.16"
escargot = { version = "0.5", features = ["test_unstable"] }
fatfs = "0.3"
os-test-framework = "0.5"
ovmf-prebuilt = "0.2"
qemu-command-builder = "11.0.0-1"
qemu-exit = "4"
roxy-loader-utils = { version = "0.1.6", path = "./utils", features = ["local-dev"] }
roxy-loader-api = { version = "0.1.6", path = "./api" }
spin = "0.10"
tap = "1"
uart_16550 = "0.6"
uefi = { version = "0.37", features = ["alloc"] }
workspace_root = "0.2"
x86_64 = "0.15"
xshell = "0.2"
