[workspace]
members = ["api","basic-kernel", "utils", "xtask"]

[package]
name = "roxy-loader"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow.workspace = true
elfloader.workspace = true
uefi.workspace = true
roxy-loader-api.workspace = true

[workspace.dependencies]
anyhow = { version = "1", default-features = false }
cargo-bin-file = "0.1"
cargo-emit = "0.2"
cargo_metadata = "0.23"
clap = { version = "4", features = ["derive"] }
elfloader = "0.16"
fatfs = "0.3"
ovmf-prebuilt = "0.2"
qemu-command-builder = "11"
roxy-loader-utils.path = "./utils"
roxy-loader-api.path = "./api"
tap = "1"
uefi = { version = "0.37", features = ["alloc", "global_allocator", "panic_handler"] }
workspace_root = "0.2"
xshell = "0.2"
