[package]
name = "xtask"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow.workspace = true
cargo_metadata.workspace = true
clap.workspace = true
escargot.workspace = true
workspace_root.workspace = true
xshell.workspace = true
roxy-loader-utils.workspace = true
qemu-command-builder.workspace = true
ovmf-prebuilt.workspace = true
fatfs.workspace = true
