[alias]
xtask = "run -p xtask --"

xrun-basic-kernel = "run -p xtask run-basic-kernel"
xbuild-basic-kernel = "run -p xtask build-basic-kernel"
xtest = "run -p xtask test"
xc-api = "run -p xtask c-api"
xpublish = "run -p xtask publish"
xbump-version = "run -p xtask bump-version"

rb = "run -p xtask run-basic-kernel"
bb = "run -p xtask build-basic-kernel"
xt = "run -p xtask test"

[unstable]
bindeps = true
