[package]
name = "roxy-loader-utils"
version = "0.1.0"
edition = "2024"
description = "Host-side utilities for building and packaging roxy-loader artifacts."
license = "MIT OR Apache-2.0"
repository = "https://github.com/RoxyOS/roxy-loader"
homepage = "https://github.com/RoxyOS/roxy-loader"
documentation = "https://docs.rs/roxy-loader-utils"

[dependencies]
anyhow.workspace = true
cargo_metadata.workspace = true
fatfs.workspace = true
tap.workspace = true

[build-dependencies]
cargo-emit.workspace = true
roxy-loader = { version = "0.1.0", path = "..", artifact = "bin", target = "x86_64-unknown-uefi" }
cargo-bin-file.workspace = true
