[package]
name = "roxy-loader-utils"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow.workspace = true
cargo_metadata.workspace = true
fatfs.workspace = true
tap.workspace = true

[build-dependencies]
cargo-emit.workspace = true
roxy-loader = { path = "..", artifact = "bin", target = "x86_64-unknown-uefi" }
cargo-bin-file.workspace = true
