[package]
name = "roxy-loader-utils"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.102"
cargo_metadata = "0.23.1"
fatfs = "0.3.6"
tap = "1.0.1"

[build-dependencies]
cargo-emit = "0.2.1"
roxy-loader = { path = "..", artifact = "bin", target = "x86_64-unknown-uefi" }
cargo-bin-file = "0.1.0"

