[package]
name = "roxy-loader-api"
version = "0.1.0"
edition = "2024"
description = "Kernel-facing API types and macros for roxy-loader."
license = "MIT OR Apache-2.0"
repository = "https://github.com/RoxyOS/roxy-loader"
homepage = "https://github.com/RoxyOS/roxy-loader"
documentation = "https://docs.rs/roxy-loader-api"

[dependencies]
